## Lab 0
Data preprocessing Guide

Course CS4082

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

##Step 1.: Read the data

In [ ]:
df = pd.read_csv("/content/mtcars.csv")

In [ ]:
print(df.head())
print(df.tail())
df.shape

               model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3

   carb
0     4
1     4
2     1
3     1
4     2
             model   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  \
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5
30   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.6   1   1     4

    carb
27     2
28     4
29     6
30     8
31     2

(32, 12)

In [ ]:
df["mpg"] = df["mpg"].fillna(df["mpg"].mean())

## Step 2: Explore the Data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   model   32 non-null     object
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64
 9   am      32 non-null     int64
 10  gear    32 non-null     int64
 11  carb    32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

In [ ]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [ ]:
df.isnull().sum()

model    0
mpg      0
cyl      0
disp     0
hp       0
drat     0
wt       0
qsec     0
vs       0
am       0
gear     0
carb     0
dtype: int64

In [ ]:
(df.isnull().sum()/len(df))*100

model    0.0
mpg      0.0
cyl      0.0
disp     0.0
hp       0.0
drat     0.0
wt       0.0
qsec     0.0
vs       0.0
am       0.0
gear     0.0
carb     0.0
dtype: float64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["model"].value_counts()

model
Mazda RX4              1
Mazda RX4 Wag          1
Datsun 710             1
Hornet 4 Drive         1
Hornet Sportabout      1
Valiant                1
Duster 360             1
Merc 240D              1
Merc 230               1
Merc 280               1
Merc 280C              1
Merc 450SE             1
Merc 450SL             1
Merc 450SLC            1
Cadillac Fleetwood     1
Lincoln Continental    1
Chrysler Imperial      1
Fiat 128               1
Honda Civic            1
Toyota Corolla         1
Toyota Corona          1
Dodge Challenger       1
AMC Javelin            1
Camaro Z28             1
Pontiac Firebird       1
Fiat X1-9              1
Porsche 914-2          1
Lotus Europa           1
Ford Pantera L         1
Ferrari Dino           1
Maserati Bora          1
Volvo 142E             1
Name: count, dtype: int64

## Step 3: Clean the Data

In [ ]:
df=df.drop_duplicates()

In [ ]:
###Handle missing values
df=df.dropna()

In [ ]:
df=df.dropna(subset=["model"])

In [ ]:
## Fill missing values
df.fillna(df["mpg"].mean(),inplace=True)
df.fillna(df["mpg"].median(),inplace=True)